//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResidentialAddress
    {
        public int RID { get; set; }
        public Nullable<int> CID { get; set; }
        public string RAddressLine1 { get; set; }
        public string RAddressLine2 { get; set; }
        public string RLandmark { get; set; }
        public string RState { get; set; }
        public string RCity { get; set; }
        public string RPincode { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
