//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecureBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int TransactionID { get; set; }
        public Nullable<long> SenderAccount { get; set; }
        public Nullable<long> RecieverAccount { get; set; }
        public string TransactionType { get; set; }
        public Nullable<double> TransactionAmount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string TransactionMode { get; set; }
        public string Maturityinstruction { get; set; }
        public string Remarks { get; set; }
    
        public virtual AccountDetail AccountDetail { get; set; }
        public virtual AccountDetail AccountDetail1 { get; set; }
    }
}
